baseURL: "https://apurvaapatil.github.io/"
languageCode: "en-us"
title: "Apurva"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
# enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  # title: "Hugo Profile"
  # description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/main-icon2.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  color:
    textColor: "#343a40"
    secondaryTextColor: "#6c757d"
    backgroundColor: "#f1f5f8"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#007bff"
    secondaryColor: "#f8f9fa"

    # darkmode:
    #   textColor: "#e4e6eb"
    #   secondaryTextColor: "#b0b3b8"
    #   backgroundColor: "#18191a"
    #   secondaryBackgroundColor: "#212529"
    #   primaryColor: "#ffffff"
    #   secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    position: absolute
    # align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    # stickyNavBar:
    #   enable : true
    #   showOnScrollUp : true
    # enableSeparator: false
    # menus:
    #   disableAbout: false
    #   disableExperience: false
    #   disableEducation: false
    #   disableProjects: false
    #   disableAchievements: false
    #   disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Apurva Patil"
    # subtitle: "I build things for the web"
    content: "I am currently pursuing my Master's in Computer Science at University of Southern California. I am a passionate software developer dedicated to creating impactful and scalable software solutions."
    image: /images/me1.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1zMX1C_9VaHL1nG8gtksEcWjeOV5zf_Up/view?usp=drive_link"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/apurvaapatil
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/apurvaapatil/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/self1.jpg"
    content: |-
      I’m currently pursuing an MS in Computer Science at USC. Before grad school, I worked as a software developer for 2 years, developing and maintaining large-scale microservice applications using Spring Boot and REST APIs to deliver critical alerts to millions of customers.

      I thrive on solving complex problems and ensuring application efficiency and reliability. My experience includes collaborating with cross-functional teams for smooth development. Passionate about learning and innovative technologies, I’m driven to contribute to impactful projects.
    skills:
      enable: true
      title: "Here are my Technical Skills:"
      items:
        - "**Languages & Frameworks:** C/C++, Java, Python, JavaScript, HTML, CSS, Angular, Spring Boot, SwiftUI \n\n"
        - "**Web API and Databases:** SQL, MongoDb, JSON, SOAP, Flask, REST API"
        - "**Developer Tools:** GIT, Android Studio, Postman, Maven, Jenkins, UNIX, GCP, Xcode, CI/CD, Docker, Figma"
        - "**Other Skills:** OOP(Object Oriented Programming), Debugging, Agile Methodologies, Software Development, Web Development, Data Analysis, Software Testing, Database Management, Cloud Computing"

  # Experience
  experience:
    enable: true
    title: "Work Experience"
    items:

      - job: "Assistant Systems Engineer"
        company: "Tata Consultancy Services (TCS)"
        companyUrl: "https://www.tcs.com/"
        date: "August 2021 - June 2023"
        info:
          enable: true
          content: "Location: Mumbai, IN"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I worked as a software developer for 2 years for a Financial Institution Client (CIBC).
          - Led collaborative efforts within an Agile team of professionals by maintaining a real-time communication application aimed to facilitate Email, SMS, Message Center, and Push Notification alerts to approximately 300,000 customers.
          - Engineered a microservice application for sending critical bank account alerts using Spring MVC architecture, reducing manual effort by 70% while ensuring scalability for future growth.
          - Spearheaded cross-functional collaboration to swiftly address and resolve defects throughout development, testing, and production phases.
          - Ensured system reliability by maintaining and supporting existing system, resolving technical issues promptly, resulting in a system uptime of 99%.
          - Technologies used - Java, Microservices, Spring/Spring Boot, Spring Batch, Jenkins, XML, UNIX, Github, Swagger, HP ALM

      # - job: "UI/UX Designer"
      #   company: "Netflix"
      #   companyUrl: "https://example.com"
      #   date: "June 2017 - Nov 2019"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"
      #   content: |
      #     I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

      #     - Lead backend developer for a product.
      #     - Created a frontend design for a product.

      # - job: "Product Designer"
      #   company: "Google"
      #   companyUrl: "https://example.com"
      #   date: "Feb 2016 - Mar 2017"
      #   content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science in Computer Science"
        school:
          name: "University Of Southern California, Los Angeles, CA"
          url: "https://www.usc.edu/"
        date: "2023 - 2025 (Expected)"
        GPA: "3.67 out of 4.0"
        content: |-
          Coursework
            - Analysis of Algorithms, Database Systems, Web Technologies, Human-Computer Interaction
      - title: "Bachelor of Engineering in Computer Engineering"
        school:
          name: "University Of Mumbai, Mumbai, IN"
          url: "https://mu.ac.in/"
        date: "2017 - 2021"
        GPA: "9.53 out of 10.0"
        content: |-
          Coursework
          - Algorithms, Database Management Systems, Machine Learning, Artificial Intelligence
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"


  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: Microsoft Certified - Azure AI Fundamentals (Dec ’22)
        # content: I solved all problems with optimal solution.
        url: https://www.credly.com/badges/ae359658-2c80-4105-ba9f-a23960a67269/public_url
        image: /images/projects/ai.webp
      - title: Machine Learning by Stanford University on Coursera (July ’21)
        url: https://coursera.org/share/3c430f3b4879eb0d15eaf0fb48e4f5e9
        image: /images/projects/ML.png

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: StockWise - Stock Trading Website & IOS App
        content: Developed an IOS application and an interactive stock trading portal allowing users to search for stocks, wishlist stocks, and trade with virtual currency.
        image: /images/projects/stock3.jpg
        featured:
          name: Demo
          link: https://assignment-3-angular-node-kfujx3fnpa-wl.a.run.app/search/home
        badges:
          - "SwiftUI"
          - "Angular"
          - "Highcharts"
          - "Bootstrap"
        # links:
        #   - icon: fa fa-envelope
        #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
        #   - icon: fab fa-github
        #     url: https://github.com/gurusabarish/hugo-profile
        #   - icon: fab fa-twitter
        #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Wordle Clone
        content: Built a Wordle game clone incorporating a Wordnik API for real-time validation of word entries.
        image: /images/projects/game1.jpg
        featured:
          name: Demo
          link: https://wordle-app-clone.netlify.app
        badges:
          - "ReactJs"
          - "REST API"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/apurvaapatil/Wordle-App

      # - title: Tourist Travel Guide
      #   content: Developed a dynamic web application using React Js that provided real-time recommendations to tourists based on user's location.
      #   image: /images/projects/profile2.jpg
      #   featured:
      #     name: Demo
      #     link: https://tour-ist.netlify.app/
      #   badges:
      #     - "ReactJs"
      #     - "REST API"
      #     - "Javascript"
      #   links:
      #     - icon: fab fa-github
      #       url: https://github.com/apurvaapatil/Travel-Guide-ReactJs

      - title: Code Sharing Platform
        content: Designed a web platform leveraging Spring boot for backend and Thymeleaf for frontend to facilitate code snippet sharing among users.
        image: /images/projects/code1.jpg
        featured:
          name: Click here to view code!
          link: https://github.com/apurvaapatil/Code-Sharing-App
        badges:
          - "Java"
          - "SpringBoot"
        links:
          - icon: fab fa-github
            url: https://github.com/apurvaapatil/Code-Sharing-App

      - title: Goodreads App Redesign - HCI
        content: Conducted User Research for the redesign of the Goodreads mobile application.
        image: /images/projects/books2.jpg
        featured:
          name: Demo
          link: https://www.figma.com/proto/zcX63Vo1DKwRJyTWVPOiQO/HCI-Assignment-3---User-suggested-changes-(Copy)?node-id=2001-689&starting-point-node-id=2001%3A689
        badges:
          - "Figma"
          - "HCI"
        links:
          - icon: fab fa-github
            url: https://github.com/apurvaapatil/Goodreads-Redesign

      - title: Amazon Sentiment Analysis
        content: Conducted sentiment analysis on Amazon reviews, showcasing the ability to derive actionable insights from complex data. Achieved 90.6% accuracy for Logistic Regression and 86.6% accuracy for Multinomial Naive Bayes.
        image: /images/projects/sentiments2.jpg
        featured:
          name: Click here to learn more!
          link: https://github.com/apurvaapatil/Amazon-Sentiment-Analysis
        badges:
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/apurvaapatil/Amazon-Sentiment-Analysis
        
      - title: Movie Recommendation System
        content: Built recommendation system using cosine similarity to recommend top five movies based on input movie given by user.
        image: /images/projects/movie1.jpg
        featured:
          name: Click here to learn more!
          link: https://github.com/apurvaapatil/movie-recommendation-system
        badges:
          - "Python"
        links:
          - icon: fab fa-github
            url: https://github.com/apurvaapatil/movie-recommendation-system

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:apurvapat99@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/apurvaapatil
      linkedin: https://www.linkedin.com/in/apurvaapatil/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>